Feature/58760 playerlist finalisierung
puzzle-bbt/puzzle-scrum-poker pull request #24
Opened 2021-12-10 08:31 UTC by lkleisa

Finalisierung Playerliste

2021-12-10 14:09 UTC, hpfammatter requested changes

2021-12-10 14:09 UTC, hpfammatter commented on frontend/src/app/components/playerlist/playerlist.component.html
>  <div class="player-list">
allgemeine Bemerkung: wir sollten für die Player List ein Grid Layout verwenden (am besten wahrscheinlich display: grid)

2021-12-10 14:09 UTC, hpfammatter commented on frontend/src/app/components/playerlist/playerlist.component.html
> +                    <div *ngIf="isGameRunning || isGameRunning == undefined; else gameIsNotRunning">
die Bedingung hier stimmt nicht, wenn eine neue Runde gestartet wird, wird immer noch der alte Kartenwert angezeigt

2021-12-10 14:09 UTC, hpfammatter commented on frontend/src/app/components/playerlist/playerlist.component.html
> +        <!--
den Kommentar gerade entfernen, ich denke im auskommentierten Code hat es ein `<ng-template>` zu viel (im ersten div)

2021-12-10 14:09 UTC, hpfammatter commented on frontend/src/app/components/playerlist/playerlist.component.html
> +                    <div *ngIf="isGameRunning || isGameRunning == undefined; else gameIsNotRunning">
-> wahrscheinlich braucht es einfach ein refresh beim gamestart

2021-12-10 14:09 UTC, hpfammatter commented on frontend/src/app/components/playerlist/playerlist.component.ts
> +        /*
Kommentar gerade entfernen

2021-12-10 14:09 UTC, hpfammatter commented on frontend/src/app/components/playerlist/playerlist.component.scss
> +    border-right: 4px solid black;
Border gerade entfernen

2021-12-10 14:09 UTC, hpfammatter commented on frontend/src/app/components/playerlist/playerlist.component.html
> +                    <div *ngIf="isGameRunning || isGameRunning == undefined; else gameIsNotRunning">
vielleicht das refresh noch gerade hinzufügen

2021-12-13 14:23 UTC, tuxmatta commented
Die Aktualisierung der Angular Komponente funktioniert nach der Umstellung auf `changeDetection: ChangeDetectionStrategy.OnPush` nicht mehr. Ich mache euch ein Beispiel, sobald diese und Niklas PullRequest gemerged sind.

2021-12-13 14:24 UTC, tuxmatta commented
Merge diesen Branch, obwohl die Aktualisierung noch nicht funktioniert.

2021-12-13 14:24 UTC, merged